CREATE DATABASE IF NOT EXISTS PV_PLATFORM;
CREATE SCHEMA IF NOT EXISTS PV_PLATFORM.RAW;
CREATE SCHEMA IF NOT EXISTS PV_PLATFORM.STAGING;
CREATE SCHEMA IF NOT EXISTS PV_PLATFORM.CURATED;
CREATE WAREHOUSE IF NOT EXISTS PV_WH WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60;

CREATE OR REPLACE STORAGE INTEGRATION pv_s3_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::036991040348:role/snowflake-pv-role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://meridian-pv-platform/');

  DESC STORAGE INTEGRATION pv_s3_int;

  CREATE OR REPLACE STAGE PV_PLATFORM.RAW.S3_RAW_STAGE
  URL = 's3://meridian-pv-platform/raw/'
  STORAGE_INTEGRATION = pv_s3_int
  FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY='"');

  LIST @PV_PLATFORM.RAW.S3_RAW_STAGE;

  CREATE OR REPLACE TABLE PV_PLATFORM.RAW.ADVERSE_EVENTS_RAW (
  report_id STRING, report_received_date STRING, country STRING,
  reporter_type STRING, patient_age STRING, patient_sex STRING,
  drug_name STRING, drug_ndc_code STRING, indication STRING,
  adverse_event_term STRING, event_seriousness STRING, outcome STRING,
  onset_date STRING, batch_id STRING, manufacturing_site STRING,
  dose_amount_mg STRING, route_of_administration STRING,
  concomitant_medications STRING, causality_assessment STRING
);


COPY INTO PV_PLATFORM.RAW.ADVERSE_EVENTS_RAW
  FROM @PV_PLATFORM.RAW.S3_RAW_STAGE
  PATTERN='.*pharma_capstone_adverse_events_raw.*\.csv';

  SELECT COUNT(*) FROM PV_PLATFORM.RAW.ADVERSE_EVENTS_RAW;

  SELECT * FROM PV_PLATFORM.RAW.ADVERSE_EVENTS_RAW LIMIT 10;

  SELECT CURRENT_ACCOUNT(), CURRENT_REGION(), CURRENT_ORGANIZATION_NAME();



SHOW TABLES IN PV_PLATFORM.STAGING;
SHOW TABLES IN PV_PLATFORM.RAW;


SHOW TABLES IN PV_PLATFORM.RAW;
SELECT "name" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) ORDER BY "created_on" DESC;

CREATE OR REPLACE TABLE PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN AS
SELECT * FROM PV_PLATFORM.RAW.NODE_F3621F50_PHARMACOVIGILANCE_CAPSTONE_ADVERSE_EVENTS_CLEAN;|

CREATE OR REPLACE TABLE PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN AS
SELECT * FROM PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_ADVERSE_EVENTS_CLEAN";


SELECT COUNT(*) FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;


DROP TABLE IF EXISTS PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_ADVERSE_EVENTS_CLEAN";






CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.DIM_BATCH (
  batch_key INT IDENTITY PRIMARY KEY,
  drug_key INT NOT NULL,
  batch_id STRING NOT NULL,
  UNIQUE (drug_key, batch_id)
);

CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.DIM_SITE (
  site_key INT IDENTITY PRIMARY KEY,
  manufacturing_site STRING NOT NULL UNIQUE
);

CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.DIM_GEOGRAPHY (
  geo_key INT IDENTITY PRIMARY KEY,
  country STRING NOT NULL UNIQUE
);

CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.DIM_DATE (
  date_key INT PRIMARY KEY,
  full_date DATE,
  year INT,
  month INT,
  month_name STRING,
  week INT
);




CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.DIM_DRUG (
  drug_key INT IDENTITY PRIMARY KEY,
  drug_ndc_code STRING NOT NULL UNIQUE,
  drug_name STRING,
  indication STRING
);

CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT (
  report_id STRING PRIMARY KEY,
  drug_key INT NOT NULL,
  batch_key INT NOT NULL,
  site_key INT NOT NULL,
  geo_key INT NOT NULL,
  report_date_key INT NOT NULL,
  onset_date_key INT,
  reporter_type STRING,
  adverse_event_term STRING,
  patient_age NUMBER,
  is_age_imputed BOOLEAN,
  patient_sex STRING,
  is_sex_missing BOOLEAN,
  dose_amount_mg NUMBER,
  is_dose_missing BOOLEAN,
  route_of_administration STRING,
  concomitant_medications STRING,
  event_seriousness STRING,
  outcome STRING,
  causality_assessment STRING,
  CONSTRAINT fk_fact_drug FOREIGN KEY (drug_key) REFERENCES PV_PLATFORM.CURATED.DIM_DRUG(drug_key),
  CONSTRAINT fk_fact_batch FOREIGN KEY (batch_key) REFERENCES PV_PLATFORM.CURATED.DIM_BATCH(batch_key),
  CONSTRAINT fk_fact_site FOREIGN KEY (site_key) REFERENCES PV_PLATFORM.CURATED.DIM_SITE(site_key),
  CONSTRAINT fk_fact_geo FOREIGN KEY (geo_key) REFERENCES PV_PLATFORM.CURATED.DIM_GEOGRAPHY(geo_key),
  CONSTRAINT fk_fact_rpt_date FOREIGN KEY (report_date_key) REFERENCES PV_PLATFORM.CURATED.DIM_DATE(date_key),
  CONSTRAINT fk_fact_onset_date FOREIGN KEY (onset_date_key) REFERENCES PV_PLATFORM.CURATED.DIM_DATE(date_key)
) CLUSTER BY (report_date_key);


SHOW TABLES IN PV_PLATFORM.CURATED;




#Step 1: Populate DIM_DATE

INSERT INTO PV_PLATFORM.CURATED.DIM_DATE (date_key, full_date, year, month, month_name, week)
SELECT
  TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')) AS date_key,
  d AS full_date,
  YEAR(d) AS year,
  MONTH(d) AS month,
  MONTHNAME(d) AS month_name,
  WEEKOFYEAR(d) AS week
FROM (
  SELECT DATEADD(day, SEQ4(), '2025-01-01'::DATE) AS d
  FROM TABLE(GENERATOR(ROWCOUNT => 365))
);

SELECT COUNT(*) FROM PV_PLATFORM.CURATED.DIM_DATE;


#Step 2: Populate DIM_GEOGRAPHY

INSERT INTO PV_PLATFORM.CURATED.DIM_GEOGRAPHY (country)
SELECT DISTINCT country FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;

DESCRIBE TABLE PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;



SELECT COUNT(*) FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN_latest;

SHOW TABLES IN PV_PLATFORM.RAW LIKE '%LATEST%';



SELECT table_name, created
FROM PV_PLATFORM.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'RAW'
ORDER BY created DESC
LIMIT 10;



SELECT COUNT(*) FROM PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_ADVERSE_EVENTS_CLEAN_LATEST";

DESCRIBE TABLE PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_ADVERSE_EVENTS_CLEAN_LATEST";

CREATE OR REPLACE TABLE PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN AS
SELECT * FROM PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_ADVERSE_EVENTS_CLEAN_LATEST";


DROP TABLE IF EXISTS PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_ADVERSE_EVENTS_CLEAN_LATEST";
DROP TABLE IF EXISTS PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_AE_FINAL_CLEAN_RENAMED";
DROP TABLE IF EXISTS PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_AE_AGE_IMPUTED_BY_REPORT_ID";
DROP TABLE IF EXISTS PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_AE_AGE_IMPUTED";
DROP TABLE IF EXISTS PV_PLATFORM.RAW."node_f3621f50_PHARMACOVIGILANCE_CAPSTONE_AE_WITH_AGE_MEDIANS";

SELECT COUNT(*) FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;
DESCRIBE TABLE PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;
SHOW TABLES IN PV_PLATFORM.RAW;




##Step 1: Populate DIM_DATE
INSERT INTO PV_PLATFORM.CURATED.DIM_DATE (date_key, full_date, year, month, month_name, week)
SELECT
  TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')) AS date_key,
  d AS full_date,
  YEAR(d) AS year,
  MONTH(d) AS month,
  MONTHNAME(d) AS month_name,
  WEEKOFYEAR(d) AS week
FROM (
  SELECT DATEADD(day, SEQ4(), '2025-01-01'::DATE) AS d
  FROM TABLE(GENERATOR(ROWCOUNT => 365))
);

###Step 2: Populate DIM_GEOGRAPHY

INSERT INTO PV_PLATFORM.CURATED.DIM_GEOGRAPHY (country)
SELECT DISTINCT country FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;

##Step 3: Populate DIM_SITE

INSERT INTO PV_PLATFORM.CURATED.DIM_SITE (manufacturing_site)
SELECT DISTINCT manufacturing_site FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;

#Step 4: Populate DIM_DRUG
INSERT INTO PV_PLATFORM.CURATED.DIM_DRUG (drug_ndc_code, drug_name, indication)
SELECT DISTINCT drug_ndc_code, drug_name, indication
FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN;

#Step 5: Populate DIM_BATCH (depends on DIM_DRUG, run after Step 4)
INSERT INTO PV_PLATFORM.CURATED.DIM_BATCH (drug_key, batch_id)
SELECT DISTINCT d.drug_key, s.batch_id
FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN s
JOIN PV_PLATFORM.CURATED.DIM_DRUG d ON s.drug_ndc_code = d.drug_ndc_code;


SELECT COUNT(*) FROM PV_PLATFORM.CURATED.DIM_GEOGRAPHY;   -- expect ~9
SELECT COUNT(*) FROM PV_PLATFORM.CURATED.DIM_SITE;        -- expect 5
SELECT COUNT(*) FROM PV_PLATFORM.CURATED.DIM_DRUG;        -- expect 9
SELECT COUNT(*) FROM PV_PLATFORM.CURATED.DIM_BATCH;       -- expect somewhere around 65-68


SELECT table_schema, table_name, column_name, data_type, is_nullable, ordinal_position
FROM PV_PLATFORM.INFORMATION_SCHEMA.COLUMNS
WHERE (table_schema = 'CURATED' AND table_name IN ('DIM_DRUG', 'DIM_BATCH', 'FACT_ADVERSE_EVENT'))
   OR (table_schema = 'STAGING' AND table_name = 'ADVERSE_EVENTS_CLEAN')
ORDER BY table_schema, table_name, ordinal_position;



###Populate FACT_ADVERSE_EVENT
INSERT INTO PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT (
  report_id, drug_key, batch_key, site_key, geo_key,
  report_date_key, onset_date_key,
  reporter_type, adverse_event_term,
  patient_age, is_age_imputed,
  patient_sex, is_sex_missing,
  dose_amount_mg, is_dose_missing,
  route_of_administration, concomitant_medications,
  event_seriousness, outcome, causality_assessment
)
SELECT
  s.report_id,
  d.drug_key,
  b.batch_key,
  st.site_key,
  g.geo_key,
  TO_NUMBER(TO_CHAR(s.report_received_date, 'YYYYMMDD')) AS report_date_key,
  TO_NUMBER(TO_CHAR(s.onset_date, 'YYYYMMDD')) AS onset_date_key,
  s.reporter_type,
  s.adverse_event_term,
  s.patient_age,
  s.is_age_missing AS is_age_imputed,
  s.patient_sex,
  s.is_sex_missing,
  s.dose_amount_mg,
  s.is_dose_missing,
  s.route_of_administration,
  s.concomitant_medications,
  s.event_seriousness,
  s.outcome,
  s.causality_assessment
FROM PV_PLATFORM.STAGING.ADVERSE_EVENTS_CLEAN s
JOIN PV_PLATFORM.CURATED.DIM_DRUG d ON s.drug_ndc_code = d.drug_ndc_code
JOIN PV_PLATFORM.CURATED.DIM_BATCH b ON b.drug_key = d.drug_key AND b.batch_id = s.batch_id
JOIN PV_PLATFORM.CURATED.DIM_SITE st ON s.manufacturing_site = st.manufacturing_site
JOIN PV_PLATFORM.CURATED.DIM_GEOGRAPHY g ON s.country = g.country;


SELECT COUNT(*) FROM PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT;



##referential integrity
SELECT f.report_id
FROM PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT f
LEFT JOIN PV_PLATFORM.CURATED.DIM_DRUG d ON f.drug_key = d.drug_key
LEFT JOIN PV_PLATFORM.CURATED.DIM_BATCH b ON f.batch_key = b.batch_key
LEFT JOIN PV_PLATFORM.CURATED.DIM_SITE st ON f.site_key = st.site_key
LEFT JOIN PV_PLATFORM.CURATED.DIM_GEOGRAPHY g ON f.geo_key = g.geo_key
LEFT JOIN PV_PLATFORM.CURATED.DIM_DATE rd ON f.report_date_key = rd.date_key
LEFT JOIN PV_PLATFORM.CURATED.DIM_DATE od ON f.onset_date_key = od.date_key
WHERE d.drug_key IS NULL
   OR b.batch_key IS NULL
   OR st.site_key IS NULL
   OR g.geo_key IS NULL
   OR rd.date_key IS NULL
   OR od.date_key IS NULL;


##Quick spot-check (recommended, cheap insurance)
SELECT f.report_id, d.drug_name, b.batch_id, st.manufacturing_site, g.country, rd.full_date AS report_date
FROM PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT f
JOIN PV_PLATFORM.CURATED.DIM_DRUG d ON f.drug_key = d.drug_key
JOIN PV_PLATFORM.CURATED.DIM_BATCH b ON f.batch_key = b.batch_key
JOIN PV_PLATFORM.CURATED.DIM_SITE st ON f.site_key = st.site_key
JOIN PV_PLATFORM.CURATED.DIM_GEOGRAPHY g ON f.geo_key = g.geo_key
JOIN PV_PLATFORM.CURATED.DIM_DATE rd ON f.report_date_key = rd.date_key
LIMIT 10;   

#Step 1: Build the monthly aggregation view
CREATE OR REPLACE VIEW PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG AS
SELECT
  d.drug_ndc_code,
  d.drug_name,
  dt.year,
  dt.month,
  DATE_FROM_PARTS(dt.year, dt.month, 1) AS period_start,
  COUNT(*) AS ae_count
FROM PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT f
JOIN PV_PLATFORM.CURATED.DIM_DRUG d ON f.drug_key = d.drug_key
JOIN PV_PLATFORM.CURATED.DIM_DATE dt ON f.report_date_key = dt.date_key
GROUP BY d.drug_ndc_code, d.drug_name, dt.year, dt.month
ORDER BY d.drug_name, period_start;

SELECT * FROM PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG;


#Step 3: Create the anomaly detection model
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION pv_ae_anomaly_model(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG'),
  TIMESTAMP_COLNAME => 'PERIOD_START',
  TARGET_COLNAME => 'AE_COUNT',
  SERIES_COLNAME => 'DRUG_NDC_CODE'
);
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION pv_ae_anomaly_model(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG'),
  TIMESTAMP_COLNAME => 'PERIOD_START',
  TARGET_COLNAME => 'AE_COUNT',
  SERIES_COLNAME => 'DRUG_NDC_CODE'
);

CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.AE_SIGNAL_FLAGS AS
WITH stats AS (
  SELECT
    drug_ndc_code,
    AVG(ae_count) AS avg_count,
    STDDEV(ae_count) AS stddev_count
  FROM PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG
  GROUP BY drug_ndc_code
)
SELECT
  v.drug_ndc_code,
  v.drug_name,
  v.period_start,
  v.ae_count,
  s.avg_count,
  s.stddev_count,
  (v.ae_count - s.avg_count) / NULLIF(s.stddev_count, 0) AS z_score,
  CASE WHEN ABS((v.ae_count - s.avg_count) / NULLIF(s.stddev_count, 0)) > 2 THEN TRUE ELSE FALSE END AS is_anomaly,
  CURRENT_TIMESTAMP() AS run_ts
FROM PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG v
JOIN stats s ON v.drug_ndc_code = s.drug_ndc_code
ORDER BY ABS(z_score) DESC NULLS LAST;


SELECT * FROM PV_PLATFORM.CURATED.AE_SIGNAL_FLAGS WHERE is_anomaly = TRUE;

SELECT * FROM PV_PLATFORM.CURATED.AE_SIGNAL_FLAGS ORDER BY drug_name, period_start;



SHOW GRANTS TO ROLE ACCOUNTADMIN;

GRANT DATABASE ROLE SNOWFLAKE.ML.SNOWFLAKE_TIME_SERIES_ANOMALY_DETECTION_USER TO ROLE ACCOUNTADMIN;

SHOW FUNCTIONS LIKE '%ANOMALY%' IN SCHEMA SNOWFLAKE.ML;

SELECT CURRENT_REGION(), CURRENT_ACCOUNT_NAME(), CURRENT_AVAILABLE_ROLES();
SHOW PARAMETERS LIKE 'ENABLE_SNOWFLAKE_ML%' IN ACCOUNT;

CREATE SNOWFLAKE.ML.ANOMALY_DETECTION my_test_model(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT'),
  TIMESTAMP_COLNAME => 'REPORT_DATE_KEY',
  TARGET_COLNAME => 'PATIENT_AGE',
  SERIES_COLNAME => 'DRUG_KEY'
);

SELECT CURRENT_REGION(), CURRENT_ACCOUNT_NAME(), CURRENT_AVAILABLE_ROLES();


GRANT CREATE SNOWFLAKE.ML.ANOMALY_DETECTION ON SCHEMA PV_PLATFORM.CURATED TO ROLE ACCOUNTADMIN;
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA PV_PLATFORM.CURATED TO ROLE ACCOUNTADMIN;


CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION pv_ae_anomaly_model(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG'),
  TIMESTAMP_COLNAME => 'PERIOD_START',
  TARGET_COLNAME => 'AE_COUNT',
  SERIES_COLNAME => 'DRUG_NDC_CODE'
);

####Creating the model
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION pv_ae_anomaly_model(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG'),
  TIMESTAMP_COLNAME => 'PERIOD_START',
  TARGET_COLNAME => 'AE_COUNT',
  SERIES_COLNAME => 'DRUG_NDC_CODE',
  LABEL_COLNAME => ''  -- Required argument: leave empty for unsupervised learning
);


CALL pv_ae_anomaly_model!DETECT_ANOMALIES(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG'),
  TIMESTAMP_COLNAME => 'PERIOD_START',
  TARGET_COLNAME => 'AE_COUNT',
  SERIES_COLNAME => 'DRUG_NDC_CODE'
);



CREATE OR REPLACE VIEW PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG_TRAIN AS
SELECT * FROM PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG
WHERE period_start < '2025-10-01';

CREATE OR REPLACE VIEW PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG_EVAL AS
SELECT * FROM PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG
WHERE period_start >= '2025-10-01';

SELECT COUNT(*) FROM PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG_TRAIN;
SELECT COUNT(*) FROM PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG_EVAL;


CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION pv_ae_anomaly_model(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG_TRAIN'),
  TIMESTAMP_COLNAME => 'PERIOD_START',
  TARGET_COLNAME => 'AE_COUNT',
  SERIES_COLNAME => 'DRUG_NDC_CODE',
  LABEL_COLNAME => ''
);


CALL pv_ae_anomaly_model!DETECT_ANOMALIES(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'PV_PLATFORM.CURATED.VW_MONTHLY_AE_BY_DRUG_EVAL'),
  TIMESTAMP_COLNAME => 'PERIOD_START',
  TARGET_COLNAME => 'AE_COUNT',
  SERIES_COLNAME => 'DRUG_NDC_CODE'
);

CREATE OR REPLACE TABLE PV_PLATFORM.CURATED.AE_SIGNAL_FLAGS AS
SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SELECT * FROM PV_PLATFORM.CURATED.AE_SIGNAL_FLAGS;

SELECT COUNT(*) FROM PV_PLATFORM.CURATED.AE_SIGNAL_FLAGS;

SELECT * FROM PV_PLATFORM.CURATED.AE_SIGNAL_FLAGS WHERE IS_ANOMALY = TRUE;

SELECT drug_name FROM PV_PLATFORM.CURATED.DIM_DRUG WHERE drug_ndc_code = '60505-1122-03';

SELECT f.report_id, f.adverse_event_term, f.event_seriousness, f.outcome, f.causality_assessment
FROM PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT f
JOIN PV_PLATFORM.CURATED.DIM_DRUG d ON f.drug_key = d.drug_key
JOIN PV_PLATFORM.CURATED.DIM_DATE dt ON f.report_date_key = dt.date_key
WHERE d.drug_ndc_code = '60505-1122-03' AND dt.year = 2025 AND dt.month = 12;


SELECT DISTINCT event_seriousness FROM PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT;

##Part 2, Step 1: Serious-event-rate by country view
CREATE OR REPLACE VIEW PV_PLATFORM.CURATED.VW_SERIOUS_RATE_BY_COUNTRY AS
SELECT
  g.country,
  dt.year,
  dt.month,
  DATE_FROM_PARTS(dt.year, dt.month, 1) AS period_start,
  COUNT(*) AS total_reports,
  SUM(CASE WHEN f.event_seriousness = 'Serious' THEN 1 ELSE 0 END) AS serious_reports,
  ROUND(
    SUM(CASE WHEN f.event_seriousness = 'Serious' THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) * 100.0,
    1
  ) AS serious_rate_pct
FROM PV_PLATFORM.CURATED.FACT_ADVERSE_EVENT f
JOIN PV_PLATFORM.CURATED.DIM_GEOGRAPHY g ON f.geo_key = g.geo_key
JOIN PV_PLATFORM.CURATED.DIM_DATE dt ON f.report_date_key = dt.date_key
GROUP BY g.country, dt.year, dt.month
ORDER BY g.country, period_start;

SELECT * FROM PV_PLATFORM.CURATED.VW_SERIOUS_RATE_BY_COUNTRY ORDER BY serious_rate_pct DESC;



SELECT * FROM PV_PLATFORM.CURATED.VW_SERIOUS_RATE_BY_COUNTRY WHERE country IN ('France', 'Germany');

